### ISSUE TITLE
Invites and joins not working under some conditions

### ISSUE THREAD

**Issue by piegamesde** [girlbossceo/conduwuit#411]
These are multiple bugs which I suspect to have the same root cause: After Conduwuit leaves a "remote" room with its last user, re-joining it may be impossible.

All reproducers tested against matrix.org

## Reproducer 1 – Cannot rejoin the room

1. create empty room on another server
2. invite Conduwuit account
3. accept invitation and leave
4. make the room public
5. try to re-join via room ID (or even room alias)

Client: "Failed to join There was an error joining."
Server logs: "conduit_api::client_server::membership: We can join locally"

## Reproducer 2 – Cannot re-invite to room

1. create empty room on another server
2. invite Conduwuit account
3. accept invitation and leave
4. re-invite. The invitation will never arrive
5. Try to join via room-ID

Client: "MatrixError: [403] M_FORBIDDEN: Event is not authorized"
Server logs: conduit_api::client_server::membership: We can join locally

## Reproducer 3 – Rejoining the room leads to desync

1. Create a room on another server, make it public unlisted
2. join via ID, server will successfully join via federation
3. leave and re-join, "conduit_api::client_server::membership: We can join locally"
4. leave, make the room invite-only
8. re-join, the server will "successfully" rejoin "locally" while actually it shouldn't and so the join doesn't show up on the other server

**Comment by girlbossceo** [comment]
I believe at least 2 of these cases should be fixed on the main branch.

https://github.com/girlbossceo/conduwuit/pull/442 and https://github.com/girlbossceo/conduwuit/pull/441 have been merged

Could you see if your situation has improved on the main branch?

**Comment by piegamesde** [comment]
Works as intended. Only re-invites still don't get through, but given that I can still manually join the room I'd argue this is a separate issue.
